---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service
  template:
    metadata:
      labels:
        app: java-service
    spec:
      containers:
        - name: java-service
          image: docker.io/library/java_service:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
